/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-12 06:03:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.instructor.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680935606000L));
    _jspx_dependants.put("jar:file:/C:/YIST_SUB/YIST-main/YIST/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<!--\n");
      out.write(" // WEBSITE: https://themefisher.com\n");
      out.write(" // TWITTER: https://twitter.com/themefisher\n");
      out.write(" // FACEBOOK: https://www.facebook.com/themefisher\n");
      out.write(" // GITHUB: https://github.com/themefisher/\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("\n");
      out.write("<title>선생의 헤더바</title>\n");
      out.write("\n");
      out.write("<!-- GOOGLE FONTS -->\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Karla:400,700|Roboto\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- 얘가 목록 아이콘임 -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/material/css/materialdesignicons.min.css\"\n");
      out.write("	rel=\"stylesheet\" />\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/simplebar/simplebar.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<!-- PLUGINS CSS STYLE -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/nprogress/nprogress.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/prism/prism.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jvectormap/jquery-jvectormap-2.0.3.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/daterangepicker/daterangepicker.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/toaster/toastr.min.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- FAVICON -->\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicon.png\" rel=\"shortcut icon\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/nprogress/nprogress.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/instructor/style.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css.map\" />\n");
      out.write("\n");
      out.write("<!-- jquery -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 폴더트리 -->\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"navbar-fixed sidebar-fixed\" id=\"body\">\n");
      out.write("	<script>\n");
      out.write("		NProgress.configure({\n");
      out.write("			showSpinner : false\n");
      out.write("		});\n");
      out.write("		NProgress.start();\n");
      out.write("	</script>\n");
      out.write("		<aside class=\"left-sidebar sidebar-light\" id=\"left-sidebar\">\n");
      out.write("			<div id=\"sidebar\" class=\"sidebar sidebar-with-footer\">\n");
      out.write("\n");
      out.write("				<div class=\"app-brand\">\n");
      out.write("					<a href=\"main.ins\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/yist_logo.png\"\n");
      out.write("						alt=\"Mono\"> <span class=\"brand-name\"></span>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sidebar-left\" data-simplebar style=\"height: 100%;\">\n");
      out.write("					<!-- 왼쪽메뉴창 -->\n");
      out.write("					<ul class=\"nav sidebar-inner\" id=\"sidebar-menu\">\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"studentForm.ins\"> <i\n");
      out.write("								class=\"mdi mdi-briefcase-account-outline\"></i> <span\n");
      out.write("								class=\"nav-text\">학생</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li class=\"sider\"><a class=\"sidenav-item-link\" href=\"team.html\"> <i\n");
      out.write("								class=\"mdi mdi-account-group\"></i> <span class=\"nav-text\">학급</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"yistcheck.ins\"> <i\n");
      out.write("								class=\"mdi mdi-calendar-check\"></i> <span class=\"nav-text\">출석</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"taskForm.ins\"> <i\n");
      out.write("								class=\"mdi mdi-file-document-box-multiple\"></i> <span\n");
      out.write("								class=\"nav-text\">과제</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"examForm.ins\"> <i\n");
      out.write("								class=\"mdi mdi-pencil\"></i> <span class=\"nav-text\">시험</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"gradeForm.ins\"> <i\n");
      out.write("								class=\"mdi mdi-file-account\"></i> <span class=\"nav-text\">성적</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"chat.html\"> <i\n");
      out.write("								class=\"mdi mdi-wechat\"></i> <span class=\"nav-text\">상담</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"contacts.html\"> <i\n");
      out.write("								class=\"mdi mdi-phone\"></i> <span class=\"nav-text\">강사</span>\n");
      out.write("						</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"contacts.html\"> <i\n");
      out.write("								class=\"mdi mdi-email\"></i> <span class=\"nav-text\">학습자료</span>\n");
      out.write("						</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</aside>\n");
      out.write("		\n");
      out.write("		      <!-- Header -->\n");
      out.write("      <header class=\"main-header\" id=\"header\">\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light\" id=\"navbar\">\n");
      out.write("          <!-- Sidebar toggle button -->\n");
      out.write("          <button id=\"sidebar-toggler\" class=\"sidebar-toggle\">\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("          </button>\n");
      out.write("\n");
      out.write("		  <!-- 헤더 타이틀 -->\n");
      out.write("          <span class=\"page-title\"></span>\n");
      out.write("\n");
      out.write("          <div class=\"navbar-right \">\n");
      out.write("\n");
      out.write("            <!-- search form -->\n");
      out.write("            <div class=\"search-form\">\n");
      out.write("              <form action=\"index.html\" method=\"get\">\n");
      out.write("                <div class=\"input-group input-group-sm\" id=\"input-group-search\">\n");
      out.write("                  <input type=\"text\" autocomplete=\"off\" name=\"query\" id=\"search-input\" class=\"form-control\"\n");
      out.write("                    placeholder=\"Search...\" />\n");
      out.write("                  <div class=\"input-group-append\">\n");
      out.write("                    <button class=\"btn\" type=\"button\">/</button>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-search\">\n");
      out.write("\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Morbi leo risus</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Dapibus ac facilisis in</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Porta ac consectetur ac</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Vestibulum at eros</a>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("              </ul>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <ul class=\"nav navbar-nav\">\n");
      out.write("              <!-- Offcanvas -->\n");
      out.write("              <li class=\"custom-dropdown\">\n");
      out.write("                <a class=\"offcanvas-toggler active custom-dropdown-toggler\" data-offcanvas=\"contact-off\"\n");
      out.write("                  href=\"javascript:\">\n");
      out.write("                  <i class=\"mdi mdi-contacts icon\"></i>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"custom-dropdown\">\n");
      out.write("                <button class=\"notify-toggler custom-dropdown-toggler\">\n");
      out.write("                  <i class=\"mdi mdi-bell-outline icon\"></i>\n");
      out.write("                  <span class=\"badge badge-xs rounded-circle\">21</span>\n");
      out.write("                </button>\n");
      out.write("                <div class=\"dropdown-notify\">\n");
      out.write("\n");
      out.write("                  <header>\n");
      out.write("                    <div class=\"nav nav-underline\" id=\"nav-tab\" role=\"tablist\">\n");
      out.write("                      <a class=\"nav-item nav-link active\" id=\"all-tabs\" data-toggle=\"tab\" href=\"#all\" role=\"tab\"\n");
      out.write("                        aria-controls=\"nav-home\" aria-selected=\"true\">All (5)</a>\n");
      out.write("                      <a class=\"nav-item nav-link\" id=\"message-tab\" data-toggle=\"tab\" href=\"#message\" role=\"tab\"\n");
      out.write("                        aria-controls=\"nav-profile\" aria-selected=\"false\">Msgs (4)</a>\n");
      out.write("                      <a class=\"nav-item nav-link\" id=\"other-tab\" data-toggle=\"tab\" href=\"#other\" role=\"tab\"\n");
      out.write("                        aria-controls=\"nav-contact\" aria-selected=\"false\">Others (3)</a>\n");
      out.write("                    </div>\n");
      out.write("                  </header>\n");
      out.write("\n");
      out.write("                  <div class=\"\" data-simplebar style=\"height: 325px;\">\n");
      out.write("                    <div class=\"tab-content\" id=\"myTabContent\">\n");
      out.write("\n");
      out.write("                      <div class=\"tab-pane fade show active\" id=\"all\" role=\"tabpanel\" aria-labelledby=\"all-tabs\">\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm bg-warning-10 p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <img src=\"images/user/user-sm-02.jpg\" alt=\"User Image\">\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">조진원 님</span>\n");
      out.write("                              <span class=\"discribe\">Extremity sweetness difficult behaviour he of. On disposal of as\n");
      out.write("                                landlord horrible. Afraid at highly months do things on at.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>Just now</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 bg-light mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper bg-primary\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <i class=\"mdi mdi-calendar-check-outline\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">New event added</span>\n");
      out.write("                              <span class=\"discribe\">1/3/2014 (1pm - 2pm)</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>10 min ago...</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <img src=\"images/user/user-sm-03.jpg\" alt=\"User Image\">\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Sagge Hudson</span>\n");
      out.write("                              <span class=\"discribe\">On disposal of as landlord Afraid at highly months do things on\n");
      out.write("                                at.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>1 hrs ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info-dark\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <i class=\"mdi mdi-account-multiple-check\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Add request</span>\n");
      out.write("                              <span class=\"discribe\">Add Dany Jones as your contact.</span>\n");
      out.write("                              <div class=\"buttons\">\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm btn-success shadow-none text-white\">accept</a>\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm shadow-none\">delete</a>\n");
      out.write("                              </div>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>6 hrs ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <i class=\"mdi mdi-playlist-check\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Task complete</span>\n");
      out.write("                              <span class=\"discribe\">Afraid at highly months do things on at.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>1 hrs ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("\n");
      out.write("                      <div class=\"tab-pane fade\" id=\"message\" role=\"tabpanel\" aria-labelledby=\"message-tab\">\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <img src=\"images/user/user-sm-01.jpg\" alt=\"User Image\">\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Selena Wagner</span>\n");
      out.write("                              <span class=\"discribe\">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>15 min ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <img src=\"images/user/user-sm-03.jpg\" alt=\"User Image\">\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Sagge Hudson</span>\n");
      out.write("                              <span class=\"discribe\">On disposal of as landlord Afraid at highly months do things on\n");
      out.write("                                at.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>1 hrs ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm bg-warning-10 p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <img src=\"images/user/user-sm-02.jpg\" alt=\"User Image\">\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">John Doe</span>\n");
      out.write("                              <span class=\"discribe\">Extremity sweetness difficult behaviour he of. On disposal of as\n");
      out.write("                                landlord horrible. Afraid\n");
      out.write("                                at highly months do things on at.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>Just now</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <img src=\"images/user/user-sm-04.jpg\" alt=\"User Image\">\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Albrecht Straub</span>\n");
      out.write("                              <span class=\"discribe\"> Beatae quia natus assumenda laboriosam, nisi perferendis aliquid\n");
      out.write("                                consectetur expedita non tenetur.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>Just now</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"tab-pane fade\" id=\"other\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 bg-light mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper bg-primary\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <i class=\"mdi mdi-calendar-check-outline\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">New event added</span>\n");
      out.write("                              <span class=\"discribe\">1/3/2014 (1pm - 2pm)</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>10 min ago...</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info-dark\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <i class=\"mdi mdi-account-multiple-check\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Add request</span>\n");
      out.write("                              <span class=\"discribe\">Add Dany Jones as your contact.</span>\n");
      out.write("                              <div class=\"buttons\">\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm btn-success shadow-none text-white\">accept</a>\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm shadow-none\">delete</a>\n");
      out.write("                              </div>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>6 hrs ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <i class=\"mdi mdi-playlist-check\"></i>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"media-body\">\n");
      out.write("                            <a href=\"user-profile.html\">\n");
      out.write("                              <span class=\"title mb-0\">Task complete</span>\n");
      out.write("                              <span class=\"discribe\">Afraid at highly months do things on at.</span>\n");
      out.write("                              <span class=\"time\">\n");
      out.write("                                <time>1 hrs ago</time>...\n");
      out.write("                              </span>\n");
      out.write("                            </a>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                  <footer class=\"border-top dropdown-notify-footer\">\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center py-2 px-4\">\n");
      out.write("                      <span>Last updated 3 min ago</span>\n");
      out.write("                      <a id=\"refress-button\" href=\"javascript:\" class=\"btn mdi mdi-cached btn-refress\"></a>\n");
      out.write("                    </div>\n");
      out.write("                  </footer>\n");
      out.write("                </div>\n");
      out.write("              </li>\n");
      out.write("              <!-- User Account -->\n");
      out.write("              <li class=\"dropdown user-menu\">\n");
      out.write("                <button class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\n");
      out.write("                  <img src=\"images/user/user-xs-01.jpg\" class=\"user-image rounded-circle\" alt=\"User Image\" />\n");
      out.write("                  <span class=\"d-none d-lg-inline-block\">조진원님</span>\n");
      out.write("                </button>\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-right\">\n");
      out.write("                  <li>\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"user-profile.html\">\n");
      out.write("                      <i class=\"mdi mdi-account-outline\"></i>\n");
      out.write("                      <span class=\"nav-text\">My Profile</span>\n");
      out.write("                    </a>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"email-inbox.html\">\n");
      out.write("                      <i class=\"mdi mdi-email-outline\"></i>\n");
      out.write("                      <span class=\"nav-text\">Message</span>\n");
      out.write("                      <span class=\"badge badge-pill badge-primary\">24</span>\n");
      out.write("                    </a>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"user-activities.html\">\n");
      out.write("                      <i class=\"mdi mdi-diamond-stone\"></i>\n");
      out.write("                      <span class=\"nav-text\">Activitise</span></a>\n");
      out.write("                  </li>\n");
      out.write("                  <li>\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"user-account-settings.html\">\n");
      out.write("                      <i class=\"mdi mdi-settings\"></i>\n");
      out.write("                      <span class=\"nav-text\">Account Setting</span>\n");
      out.write("                    </a>\n");
      out.write("                  </li>\n");
      out.write("\n");
      out.write("                  <li class=\"dropdown-footer\">\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"sign-in.html\"> <i class=\"mdi mdi-logout\"></i> Log Out </a>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("      </header>\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/simplebar/simplebar.min.js\"></script>\n");
      out.write("	  <script src=\"https://unpkg.com/hotkeys-js/dist/hotkeys.min.js\"></script>\n");
      out.write("	\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/circle-progress/circle-progress.js\"></script>\n");
      out.write("	\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/mono.js\"></script>\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chart.js\"></script>\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/map.js\"></script>\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/custom.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
