/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-04-18 03:54:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.instructor.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1681785465212L));
    _jspx_dependants.put("jar:file:/C:/YIST/YIST/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write(" // WEBSITE: https://themefisher.com\r\n");
      out.write(" // TWITTER: https://twitter.com/themefisher\r\n");
      out.write(" // FACEBOOK: https://www.facebook.com/themefisher\r\n");
      out.write(" // GITHUB: https://github.com/themefisher/\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("<title>선생의 헤더바</title>\r\n");
      out.write("\r\n");
      out.write("<!-- GOOGLE FONTS -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Karla:400,700|Roboto\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- 얘가 목록 아이콘임 -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/material/css/materialdesignicons.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/simplebar/simplebar.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<!-- PLUGINS CSS STYLE -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/nprogress/nprogress.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/prism/prism.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jvectormap/jquery-jvectormap-2.0.3.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/daterangepicker/daterangepicker.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.quilljs.com/1.3.6/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/toaster/toastr.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- FAVICON -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicon.png\" rel=\"shortcut icon\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/nprogress/nprogress.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/instructor/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css.map\" />\r\n");
      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 폴더트리 -->\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"navbar-fixed sidebar-fixed\" id=\"body\">\r\n");
      out.write("	<script>\r\n");
      out.write("		NProgress.configure({\r\n");
      out.write("			showSpinner : false\r\n");
      out.write("		});\r\n");
      out.write("		NProgress.start();\r\n");
      out.write("	</script>\r\n");
      out.write("		<aside class=\"left-sidebar sidebar-light\" id=\"left-sidebar\">\r\n");
      out.write("			<div id=\"sidebar\" class=\"sidebar sidebar-with-footer\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"app-brand\">\r\n");
      out.write("					<a href=\"main.ins\"> <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/yist_logo.png\"\r\n");
      out.write("						alt=\"Mono\"> <span class=\"brand-name\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"sidebar-left\" data-simplebar style=\"height: 100%;\">\r\n");
      out.write("					<!-- 왼쪽메뉴창 -->\r\n");
      out.write("					<ul class=\"nav sidebar-inner\" id=\"sidebar-menu\">\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"studentForm.ins\"> <i\r\n");
      out.write("								class=\"mdi mdi-briefcase-account-outline\"></i> <span\r\n");
      out.write("								class=\"nav-text\">학생</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"sider\"><a class=\"sidenav-item-link\" href=\"teacher.ins\"> <i\r\n");
      out.write("								class=\"mdi mdi-account-group\"></i> <span class=\"nav-text\">강사</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"yistcheck.ins\"> <i\r\n");
      out.write("								class=\"mdi mdi-calendar-check\"></i> <span class=\"nav-text\">출석</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"taskForm.ins\"> <i\r\n");
      out.write("								class=\"mdi mdi-file-document-box-multiple\"></i> <span\r\n");
      out.write("								class=\"nav-text\">과제</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"examForm.ins\"> <i\r\n");
      out.write("								class=\"mdi mdi-pencil\"></i> <span class=\"nav-text\">시험</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"gradeForm.ins\"> <i\r\n");
      out.write("								class=\"mdi mdi-file-account\"></i> <span class=\"nav-text\">성적</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"chat.html\"> <i\r\n");
      out.write("								class=\"mdi mdi-wechat\"></i> <span class=\"nav-text\">상담</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"contacts.html\"> <i\r\n");
      out.write("								class=\"mdi mdi-phone\"></i> <span class=\"nav-text\">강사</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<li><a class=\"sidenav-item-link\" href=\"contacts.html\"> <i\r\n");
      out.write("								class=\"mdi mdi-email\"></i> <span class=\"nav-text\">학습자료</span>\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</aside>\r\n");
      out.write("		\r\n");
      out.write("		      <!-- Header -->\r\n");
      out.write("      <header class=\"main-header\" id=\"header\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light\" id=\"navbar\">\r\n");
      out.write("          <!-- Sidebar toggle button -->\r\n");
      out.write("          <button id=\"sidebar-toggler\" class=\"sidebar-toggle\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("		  <!-- 헤더 타이틀 -->\r\n");
      out.write("          <span class=\"page-title\"></span>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"navbar-right \">\r\n");
      out.write("\r\n");
      out.write("            <!-- search form -->\r\n");
      out.write("            <div class=\"search-form\">\r\n");
      out.write("              <form action=\"index.html\" method=\"get\">\r\n");
      out.write("                <div class=\"input-group input-group-sm\" id=\"input-group-search\">\r\n");
      out.write("                  <input type=\"text\" autocomplete=\"off\" name=\"query\" id=\"search-input\" class=\"form-control\"\r\n");
      out.write("                    placeholder=\"Search...\" />\r\n");
      out.write("                  <div class=\"input-group-append\">\r\n");
      out.write("                    <button class=\"btn\" type=\"button\">/</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-search\">\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Morbi leo risus</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Dapibus ac facilisis in</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Porta ac consectetur ac</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <a class=\"nav-link\" href=\"index.html\">Vestibulum at eros</a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-nav\">\r\n");
      out.write("              <!-- Offcanvas -->\r\n");
      out.write("              <li class=\"custom-dropdown\">\r\n");
      out.write("                <a class=\"offcanvas-toggler active custom-dropdown-toggler\" data-offcanvas=\"contact-off\"\r\n");
      out.write("                  href=\"javascript:\">\r\n");
      out.write("                  <i class=\"mdi mdi-contacts icon\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"custom-dropdown\">\r\n");
      out.write("                <button class=\"notify-toggler custom-dropdown-toggler\">\r\n");
      out.write("                  <i class=\"mdi mdi-bell-outline icon\"></i>\r\n");
      out.write("                  <span class=\"badge badge-xs rounded-circle\">21</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"dropdown-notify\">\r\n");
      out.write("\r\n");
      out.write("                  <header>\r\n");
      out.write("                    <div class=\"nav nav-underline\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("                      <a class=\"nav-item nav-link active\" id=\"all-tabs\" data-toggle=\"tab\" href=\"#all\" role=\"tab\"\r\n");
      out.write("                        aria-controls=\"nav-home\" aria-selected=\"true\">All (5)</a>\r\n");
      out.write("                      <a class=\"nav-item nav-link\" id=\"message-tab\" data-toggle=\"tab\" href=\"#message\" role=\"tab\"\r\n");
      out.write("                        aria-controls=\"nav-profile\" aria-selected=\"false\">Msgs (4)</a>\r\n");
      out.write("                      <a class=\"nav-item nav-link\" id=\"other-tab\" data-toggle=\"tab\" href=\"#other\" role=\"tab\"\r\n");
      out.write("                        aria-controls=\"nav-contact\" aria-selected=\"false\">Others (3)</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </header>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"\" data-simplebar style=\"height: 325px;\">\r\n");
      out.write("                    <div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"tab-pane fade show active\" id=\"all\" role=\"tabpanel\" aria-labelledby=\"all-tabs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm bg-warning-10 p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <img src=\"images/user/user-sm-02.jpg\" alt=\"User Image\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">조진원 님</span>\r\n");
      out.write("                              <span class=\"discribe\">Extremity sweetness difficult behaviour he of. On disposal of as\r\n");
      out.write("                                landlord horrible. Afraid at highly months do things on at.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>Just now</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 bg-light mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper bg-primary\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <i class=\"mdi mdi-calendar-check-outline\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">New event added</span>\r\n");
      out.write("                              <span class=\"discribe\">1/3/2014 (1pm - 2pm)</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>10 min ago...</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <img src=\"images/user/user-sm-03.jpg\" alt=\"User Image\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Sagge Hudson</span>\r\n");
      out.write("                              <span class=\"discribe\">On disposal of as landlord Afraid at highly months do things on\r\n");
      out.write("                                at.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>1 hrs ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info-dark\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <i class=\"mdi mdi-account-multiple-check\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Add request</span>\r\n");
      out.write("                              <span class=\"discribe\">Add Dany Jones as your contact.</span>\r\n");
      out.write("                              <div class=\"buttons\">\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm btn-success shadow-none text-white\">accept</a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm shadow-none\">delete</a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>6 hrs ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <i class=\"mdi mdi-playlist-check\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Task complete</span>\r\n");
      out.write("                              <span class=\"discribe\">Afraid at highly months do things on at.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>1 hrs ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"tab-pane fade\" id=\"message\" role=\"tabpanel\" aria-labelledby=\"message-tab\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <img src=\"images/user/user-sm-01.jpg\" alt=\"User Image\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Selena Wagner</span>\r\n");
      out.write("                              <span class=\"discribe\">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>15 min ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <img src=\"images/user/user-sm-03.jpg\" alt=\"User Image\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Sagge Hudson</span>\r\n");
      out.write("                              <span class=\"discribe\">On disposal of as landlord Afraid at highly months do things on\r\n");
      out.write("                                at.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>1 hrs ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm bg-warning-10 p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <img src=\"images/user/user-sm-02.jpg\" alt=\"User Image\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">John Doe</span>\r\n");
      out.write("                              <span class=\"discribe\">Extremity sweetness difficult behaviour he of. On disposal of as\r\n");
      out.write("                                landlord horrible. Afraid\r\n");
      out.write("                                at highly months do things on at.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>Just now</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <img src=\"images/user/user-sm-04.jpg\" alt=\"User Image\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Albrecht Straub</span>\r\n");
      out.write("                              <span class=\"discribe\"> Beatae quia natus assumenda laboriosam, nisi perferendis aliquid\r\n");
      out.write("                                consectetur expedita non tenetur.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>Just now</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"tab-pane fade\" id=\"other\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 bg-light mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper bg-primary\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <i class=\"mdi mdi-calendar-check-outline\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">New event added</span>\r\n");
      out.write("                              <span class=\"discribe\">1/3/2014 (1pm - 2pm)</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>10 min ago...</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info-dark\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <i class=\"mdi mdi-account-multiple-check\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Add request</span>\r\n");
      out.write("                              <span class=\"discribe\">Add Dany Jones as your contact.</span>\r\n");
      out.write("                              <div class=\"buttons\">\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm btn-success shadow-none text-white\">accept</a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-sm shadow-none\">delete</a>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>6 hrs ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"media media-sm p-4 mb-0\">\r\n");
      out.write("                          <div class=\"media-sm-wrapper bg-info\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <i class=\"mdi mdi-playlist-check\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"media-body\">\r\n");
      out.write("                            <a href=\"user-profile.html\">\r\n");
      out.write("                              <span class=\"title mb-0\">Task complete</span>\r\n");
      out.write("                              <span class=\"discribe\">Afraid at highly months do things on at.</span>\r\n");
      out.write("                              <span class=\"time\">\r\n");
      out.write("                                <time>1 hrs ago</time>...\r\n");
      out.write("                              </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <footer class=\"border-top dropdown-notify-footer\">\r\n");
      out.write("                    <div class=\"d-flex justify-content-between align-items-center py-2 px-4\">\r\n");
      out.write("                      <span>Last updated 3 min ago</span>\r\n");
      out.write("                      <a id=\"refress-button\" href=\"javascript:\" class=\"btn mdi mdi-cached btn-refress\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </footer>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("              <!-- User Account -->\r\n");
      out.write("              <li class=\"dropdown user-menu\">\r\n");
      out.write("                <button class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                  <img src=\"images/user/user-xs-01.jpg\" class=\"user-image rounded-circle\" alt=\"User Image\" />\r\n");
      out.write("                  <span class=\"d-none d-lg-inline-block\">조진원님</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"user-profile.html\">\r\n");
      out.write("                      <i class=\"mdi mdi-account-outline\"></i>\r\n");
      out.write("                      <span class=\"nav-text\">My Profile</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"email-inbox.html\">\r\n");
      out.write("                      <i class=\"mdi mdi-email-outline\"></i>\r\n");
      out.write("                      <span class=\"nav-text\">Message</span>\r\n");
      out.write("                      <span class=\"badge badge-pill badge-primary\">24</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"user-activities.html\">\r\n");
      out.write("                      <i class=\"mdi mdi-diamond-stone\"></i>\r\n");
      out.write("                      <span class=\"nav-text\">Activitise</span></a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"user-account-settings.html\">\r\n");
      out.write("                      <i class=\"mdi mdi-settings\"></i>\r\n");
      out.write("                      <span class=\"nav-text\">Account Setting</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("\r\n");
      out.write("                  <li class=\"dropdown-footer\">\r\n");
      out.write("                    <a class=\"dropdown-link-item\" href=\"sign-in.html\"> <i class=\"mdi mdi-logout\"></i> Log Out </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </header>\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/simplebar/simplebar.min.js\"></script>\r\n");
      out.write("	  <script src=\"https://unpkg.com/hotkeys-js/dist/hotkeys.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/circle-progress/circle-progress.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/mono.js\"></script>\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chart.js\"></script>\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/map.js\"></script>\r\n");
      out.write("	  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
