/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-13 06:11:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>로그인 선택창</title>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("div.title h6 {\n");
      out.write("    font-size: 50px;\n");
      out.write("    color: #02068D;\n");
      out.write("    font-weight: 600;\n");
      out.write("    background: url() no-repeat 50% 100%;\n");
      out.write("    line-height: 1.3;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.title .titleP {\n");
      out.write("    font-size: 13.5px;\n");
      out.write("    color: #02068D;\n");
      out.write("    line-height: 1.5;\n");
      out.write("    margin-top: 30px;\n");
      out.write("    font-weight: 300;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logincell{\n");
      out.write("    margin-left: 220px;\n");
      out.write("    margin-top: 40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logincell ul {\n");
      out.write("    overflow: hidden;\n");
      out.write("    margin: 0 auto;\n");
      out.write("    width: 1084px;\n");
      out.write("    list-style:none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logincell ul li {\n");
      out.write("    float: left;\n");
      out.write("    margin: 0 15px;\n");
      out.write("    width: 241px;\n");
      out.write("    border-top: 3px solid #02068D;\n");
      out.write("    border-bottom: 2px solid #a0a0a0;\n");
      out.write("    height: 193px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logincell ul li p {\n");
      out.write("    margin-top: 48px;\n");
      out.write("    height: 50px;\n");
      out.write("    font-size: 21px;\n");
      out.write("    font-weight: 600;\n");
      out.write("    color: #373737;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".sbtn{\n");
      out.write("    height: 35px;\n");
      out.write("    line-height: 15px;\n");
      out.write("    color: #ffffff;\n");
      out.write("    background-color: #619fe1;\n");
      out.write("    border-color: #619fe1;\n");
      out.write("    padding: 0.36rem 2rem;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    font-weight: 400;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".gbtn{\n");
      out.write("    height: 35px;\n");
      out.write("    line-height: 15px;\n");
      out.write("    color: #ffffff;\n");
      out.write("    background-color: #02068D;\n");
      out.write("    border-color: #02068D;\n");
      out.write("    padding: 0.36rem 2rem;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    font-weight: 400;\n");
      out.write("}   \n");
      out.write("\n");
      out.write(".tbtn{\n");
      out.write("    height: 35px;\n");
      out.write("    line-height: 15px;\n");
      out.write("    color: #ffffff;\n");
      out.write("    background-color: #2323a9;\n");
      out.write("    border-color: #2323a9;\n");
      out.write("    padding: 0.36rem 2rem;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    font-weight: 400;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #ffffff;\">\n");
      out.write("	<div class=\"contents\">\n");
      out.write("        <div class=\"title\">\n");
      out.write("            <h6 align=\"center\">YIST</h6>\n");
      out.write("            <p class=\"titlep\" align=\"center\">\n");
      out.write("                YIST 에서는 수강생들을 위해 다양한 할인혜택과 정부 지원 서비를 연계하여<br>\n");
      out.write("                온-오프라인의 수강료 절감 등 다양한 혜택과 부가 서비스를 제공하고 있습니다.\n");
      out.write("            </p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"logincell\">\n");
      out.write("            <ul>\n");
      out.write("                <li>\n");
      out.write("                    <p>학생 로그인</p>\n");
      out.write("                    <a href=\"login.ins\" class=\"next_join\" title=\"다음단계\"><button class=\"sbtn\">로그인</button></a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <p>강사 로그인</p>\n");
      out.write("                    <a href=\"login.ins\" class=\"next_join\" title=\"다음단계\"><button class=\"tbtn\">로그인</button></a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <p>관리자 로그인</p>\n");
      out.write("                    <a href=\"login.ins\" class=\"next_join\" title=\"다음단계\"><button class=\"gbtn\">로그인</button></a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>   \n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
