/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-13 05:58:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LOGIN_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로그인 선택창</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("div.title h6 {\r\n");
      out.write("    font-size: 50px;\r\n");
      out.write("    color: #02068D;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    line-height: 1.3;\r\n");
      out.write("    margin-bottom: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.title .titleP {\r\n");
      out.write("    font-size: 13.5px;\r\n");
      out.write("    color: #02068D;\r\n");
      out.write("    line-height: 1.5;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gbtn{\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    line-height: 15px;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    background-color: #02068D;\r\n");
      out.write("    border-color: #02068D;\r\n");
      out.write("    padding: 0.4rem 4rem;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    margin-top: 25px;\r\n");
      out.write("    margin-left: 70px;\r\n");
      out.write("}   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".logincell{\r\n");
      out.write("    border: 2px solid #02068D;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    margin-left: 600px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logincell ul {\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    width: 700px;\r\n");
      out.write("    list-style:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logincell ul li {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    border-bottom: 2px solid #02068D;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    margin-left: 15px;\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write(".logincell ul li a{\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".id_password input{\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"contents\">\r\n");
      out.write("        <div class=\"title\">\r\n");
      out.write("            <h6 align=\"center\">YIST</h6>\r\n");
      out.write("            <p class=\"titlep\" align=\"center\">\r\n");
      out.write("                YIST 에서는 수강생들을 위해 다양한 할인혜택과 정부 지원 서비를 연계하여<br>\r\n");
      out.write("                온-오프라인의 수강료 절감 등 다양한 혜택과 부가 서비스를 제공하고 있습니다.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"logincell\" align=\"center\">\r\n");
      out.write("           <div class=\"id_password\" align=\"center\">\r\n");
      out.write("            <br><br>\r\n");
      out.write("                            아이디&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"text\" id=\"id\" name=\"id\" onkeypress=\"f_login();\" placeholder=\"아이디 (*이메일 형식 입력불가)\" autofocus=\"\">\r\n");
      out.write("                            <br>\r\n");
      out.write("                            비밀번호 <input type=\"password\" id=\"password\" name=\"password\" onkeypress=\"f_login();\" placeholder=\"비밀번호\" style=\"margin-top:8px;\">\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <a href=\"\"><button class=\"gbtn\">로그인</button></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <ul align=\"center\">\r\n");
      out.write("                <li><a href=\"\" style=\"text-decoration-line:none;\">아이디찾기</a></li>\r\n");
      out.write("                <li><a href=\"\" style=\"text-decoration-line:none;\">비밀번호찾기</a></li>\r\n");
      out.write("                <li><a href=\"\" style=\"text-decoration-line:none;\">회원가입</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>   \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
