/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-11 05:12:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>선생메인</title>\n");
      out.write("<style>\n");
      out.write("\n");
      out.write("\n");
      out.write(".mLeft .mtody {\n");
      out.write("    position: relative;\n");
      out.write("    width: 380px;\n");
      out.write("    height: 150px;\n");
      out.write("    padding: 30px 30px 0;\n");
      out.write("    border-width: 1px;\n");
      out.write("    border-color: #e8ebe9;\n");
      out.write("    border-radius: 3px;\n");
      out.write("    background: #a9a9a9;\n");
      out.write("	margin: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn_attend a {\n");
      out.write("    display: block;\n");
      out.write("    padding-left: 7px;\n");
      out.write("    background: url(/LMS/images/icon_td_check.png) no-repeat 18px 33px;\n");
      out.write("    color: #FFFFFF;\n");
      out.write("    font-size: 17px;\n");
      out.write("	font-weight: 500;\n");
      out.write("    text-decoration: none;\n");
      out.write("    line-height: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn_attend {\n");
      out.write("    position: absolute;\n");
      out.write("    top: 40px;\n");
      out.write("    right: 20px;\n");
      out.write("    width: 120px;\n");
      out.write("    height: 80px;\n");
      out.write("    border-width: 0px;\n");
      out.write("    border-color: #FFFFFF;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    background-color: #02068D;\n");
      out.write("    font-size: 14px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mconBox1 {\n");
      out.write("	width: 380px;\n");
      out.write("    height: 150px;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    padding: 20px;\n");
      out.write("    border-width: 1px;\n");
      out.write("    border-style: solid;\n");
      out.write("    border-color: #ebebeb;\n");
      out.write("    border-radius: 3px;\n");
      out.write("    background: #fff;\n");
      out.write("	margin-left: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mconBox2 {\n");
      out.write("	width: 380px;\n");
      out.write("    height: 150px;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    padding: 20px;\n");
      out.write("    border-width: 1px;\n");
      out.write("    border-style: solid;\n");
      out.write("    border-color: #ebebeb;\n");
      out.write("    border-radius: 3px;\n");
      out.write("    background: #fff;\n");
      out.write("	margin-left: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".all_member {\n");
      out.write("	margin-top: 10px;\n");
      out.write("    float: left;\n");
      out.write("    width: 120px;\n");
      out.write("    margin-left: 5px;\n");
      out.write("    padding: 0 0 62px 0;\n");
      out.write("	background: url(https://cdn-icons-png.flaticon.com/512/1189/1189981.png) no-repeat right bottom;\n");
      out.write("	background-size: 45%;\n");
      out.write("	background-position: right bottom 8px;\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write(".mNum1 {\n");
      out.write("    color: #02068D;\n");
      out.write("    font-size: 30px;\n");
      out.write("    font-family: 'Rubik', sans-serif;\n");
      out.write("    line-height: 30px;\n");
      out.write("    cursor: pointer;\n");
      out.write("	font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".all_lesson {\n");
      out.write("	margin-top: 10px;\n");
      out.write("	margin-left: 50px;\n");
      out.write("    float: left;\n");
      out.write("    width: 150px;\n");
      out.write("    padding: 0 0 62px 0;\n");
      out.write("	background: url(https://cdn-icons-png.flaticon.com/512/1903/1903990.png) no-repeat;\n");
      out.write("	background-size: 45%;\n");
      out.write("	background-position: right bottom 3px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".all_check {\n");
      out.write("	margin-top: 10px;\n");
      out.write("	margin-left: 50px;\n");
      out.write("    float: left;\n");
      out.write("    width: 150px;\n");
      out.write("    padding: 0 0 62px 0;\n");
      out.write("	background: url(https://cdn-icons-png.flaticon.com/512/1903/1903990.png) no-repeat;\n");
      out.write("	background-size: 45%;\n");
      out.write("	background-position: right bottom 3px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".all_nocheck {\n");
      out.write("	margin-top: 10px;\n");
      out.write("	margin-left: 50px;\n");
      out.write("    float: left;\n");
      out.write("    width: 150px;\n");
      out.write("    padding: 0 0 62px 0;\n");
      out.write("	background: url(https://cdn-icons-png.flaticon.com/512/1903/1903990.png) no-repeat;\n");
      out.write("	background-size: 45%;\n");
      out.write("	background-position: right bottom 3px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".st_attend {\n");
      out.write("    float: left;\n");
      out.write("    width: 185px;\n");
      out.write("    height: 120px;\n");
      out.write("    background: url(/LMS/images/bg_st_attend.png) no-repeat 104px 90px #fff;\n");
      out.write("    margin-left: 30px;\n");
      out.write("    border-radius: 10px;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("\n");
      out.write(".st_absence {\n");
      out.write("    float: left;\n");
      out.write("    width: 180px;\n");
      out.write("    height: 120px;\n");
      out.write("    background: url(/LMS/images/bg_st_absence.png) no-repeat 104px 90px #fff;\n");
      out.write("    border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<body class=\"navbar-fixed sidebar-fixed\" id=\"body\">\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "instructor/common/header.jsp", out, false);
      out.write("\n");
      out.write("	\n");
      out.write("	<div style=\"height:1000px; margin-left: 252px;\">\n");
      out.write("		<br><br>\n");
      out.write("	<div class=\"mLeft\" >\n");
      out.write("		<div class=\"mtody\" style=\"border-radius: 10px;\">\n");
      out.write("			<h1 style=\"font-weight: 600;\">today</h1>\n");
      out.write("		<div class=\"mday_date\" style=\"font-size: 23px; color: white;\">2023.03.29</div>\n");
      out.write("		<div class=\"week\" style=\"font-size: 15px; color: white;\">Wendnesday</div>\n");
      out.write("		<div class=\"btn_attend\">\n");
      out.write("			<a href=\"\"><i class=\"mdi mdi-calendar-check\"></i>출석체크</a>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"mconBox1\" style=\"border-radius: 10px;\">\n");
      out.write("			<div class=\"all_member\">\n");
      out.write("				<h5 style=\"font-weight: 600;\">전체수강생</h5>\n");
      out.write("				<div class=\"mNum1\">1</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"all_lesson\">\n");
      out.write("				<h5 style=\"font-weight: 600;\">개설학급</h5>\n");
      out.write("				<div class=\"mNum1\">1</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"st_attend mconBox2\">\n");
      out.write("			<h5 style=\"font-weight: 600;\">출석생</h2>\n");
      out.write("			<div class=\"mNum1\">0</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"st_absence mconBox2\">\n");
      out.write("			<h5 style=\"font-weight: 600;\">결석생</h2>\n");
      out.write("			<div class=\"mNum1\">0</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
