/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-10 01:31:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.instructor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class examForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"page-wrapper\">\n");
      out.write("		<div class=\"wrapper\">\n");
      out.write("			<!-- 헤더 -->\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../instructor/common/header.jsp", out, false);
      out.write("\n");
      out.write("			\n");
      out.write("			<div class=\"content-wrapper table-hover\">\n");
      out.write("        <div class=\"content\"><!-- For Components documentaion -->\n");
      out.write("          <!-- 메인 -->\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col\">\n");
      out.write("              <div align=\"center\" style=\"font-size: 25px; color: black;\">평가목록</div>\n");
      out.write("              <hr>\n");
      out.write("              <table class=\"table\" style=\"text-align: center;\">\n");
      out.write("                <thead style=\"background-color: lightgray;\">\n");
      out.write("                  <tr>\n");
      out.write("                    <th scope=\"col\">번호</th>\n");
      out.write("                    <th scope=\"col\">과목</th>\n");
      out.write("                    <th scope=\"col\">평가명</th>\n");
      out.write("                    <th scope=\"col\">구분</th>\n");
      out.write("                    <th scope=\"col\">평가일</th>\n");
      out.write("                    <th scope=\"col\">평가</th>\n");
      out.write("                  </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                  <tr>\n");
      out.write("                    <td scope=\"row\">1</td>\n");
      out.write("                    <td>자바기초</td>\n");
      out.write("                    <td>자료형과 연산자</td>\n");
      out.write("                    <td>서술형</td>\n");
      out.write("                    <td>2023-04-01</td>\n");
      out.write("                    <td>\n");
      out.write("                      <button type=\"button\" class=\"test-start mb-1 btn btn-pill btn-primary\" style=\"height: 25px; line-height: 10px;\">시작</button>\n");
      out.write("                      <button type=\"button\" class=\"test-score mb-1 btn btn-pill btn-secondary\" data-toggle=\"modal\" data-target=\"#examModal\" style=\"height: 25px; line-height: 10px;\" disabled>채점</button>\n");
      out.write("                      <!-- 채점 모달 -->\n");
      out.write("                      <div class=\"modal fade\" id=\"examModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                        aria-hidden=\"true\">\n");
      out.write("                        <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                          <div class=\"modal-content\">\n");
      out.write("                            <div class=\"modal-header\">\n");
      out.write("                              <h5 class=\"modal-title\" id=\"exampleModalLabel\">[자바기초] 자료형과 연산자</h5>\n");
      out.write("                              <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                                <span aria-hidden=\"true\">×</span>\n");
      out.write("                              </button>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"modal-body\">\n");
      out.write("                              <!-- 시험참여 학생 목록 -->\n");
      out.write("                              <div class=\"table-hover\">\n");
      out.write("                                <table class=\"table\">\n");
      out.write("                                  <thead style=\"background-color: darkgray;\">\n");
      out.write("                                    <tr>\n");
      out.write("                                      <th scope=\"col\">번호</th>\n");
      out.write("                                      <th scope=\"col\">이름</th>\n");
      out.write("                                      <th scope=\"col\">점수</th>\n");
      out.write("                                      <th scope=\"col\">상태</th>\n");
      out.write("                                      <th scope=\"col\"></th>\n");
      out.write("                                    </tr>\n");
      out.write("                                  </thead>\n");
      out.write("                                  <tbody>\n");
      out.write("                                    <!-- 미완료시 채점 비활성화 -->\n");
      out.write("                                    <tr>\n");
      out.write("                                      <td scope=\"row\">1</td>\n");
      out.write("                                      <td>조진원</td>\n");
      out.write("                                      <td>0/100</td>\n");
      out.write("                                      <td>미완료</td>\n");
      out.write("                                      <td><button type=\"button\" class=\"mb-1 btn btn-pill btn-primary\" disabled>채점</button></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <!-- 완료시 채점 활성화 -->\n");
      out.write("                                    <tr>\n");
      out.write("                                      <td scope=\"row\">2</td>\n");
      out.write("                                      <td>김진원</td>\n");
      out.write("                                      <td>0/100</td>\n");
      out.write("                                      <td>완료</td>\n");
      out.write("                                      <td><button type=\"button\" class=\"mb-1 btn btn-pill btn-primary\" data-toggle=\"modal\" data-target=\"#score1\">채점</button></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    \n");
      out.write("                                    <!-- 채점후 미통과 -->\n");
      out.write("                                    <tr>\n");
      out.write("                                      <td scope=\"row\">2</td>\n");
      out.write("                                      <td>박진원</td>\n");
      out.write("                                      <td>50/100</td>\n");
      out.write("                                      <td>완료</td>\n");
      out.write("                                      <td><button type=\"button\" class=\"mb-1 btn btn-pill btn-primary\" data-toggle=\"modal\" data-target=\"#score2\">채점</button></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                    <!-- 채점후 통과 -->\n");
      out.write("                                    <tr>\n");
      out.write("                                      <td scope=\"row\">3</td>\n");
      out.write("                                      <td>이진원</td>\n");
      out.write("                                      <td>80/100</td>\n");
      out.write("                                      <td>완료</td>\n");
      out.write("                                      <td><button type=\"button\" class=\"mb-1 btn btn-pill btn-primary\">채점</button></td>\n");
      out.write("                                    </tr>\n");
      out.write("                                  </tbody>\n");
      out.write("                                </table>\n");
      out.write("                              </div>\n");
      out.write("                              <!-- 시험참여 학생 목록 끝 -->\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"modal-footer\">\n");
      out.write("                              <button type=\"button\" class=\"btn btn-danger btn-pill\" data-dismiss=\"modal\">닫기</button>\n");
      out.write("                              <button type=\"button\" class=\"btn btn-primary btn-pill\" disabled>채점완료</button>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                      <button type=\"button\" class=\"test-end mb-1 btn btn-pill btn-primary\" style=\"height: 25px; line-height: 10px;\" disabled>종료</button>\n");
      out.write("                    </td>\n");
      out.write("                  </tr>\n");
      out.write("\n");
      out.write("                  <tr>\n");
      out.write("                    <td scope=\"row\">2</td>\n");
      out.write("                    <td>자바기초</td>\n");
      out.write("                    <td>조건문과 반복문</td>\n");
      out.write("                    <td>서술형</td>\n");
      out.write("                    <td>2023-04-11</td>\n");
      out.write("                    <td>\n");
      out.write("                      <button type=\"button\" class=\"test-start mb-1 btn btn-pill btn-primary\" style=\"height: 25px; line-height: 10px;\" disabled>시작</button>\n");
      out.write("                      <button type=\"button\" class=\"test-score mb-1 btn btn-pill btn-secondary\" style=\"height: 25px; line-height: 10px;\" disabled>채점</button>\n");
      out.write("                      <button type=\"button\" class=\"test-end mb-1 btn btn-pill btn-primary\" style=\"height: 25px; line-height: 10px;\" disabled>종료</button>\n");
      out.write("                    </td>\n");
      out.write("                  </tr>\n");
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("              </table>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("            						<!-- 채점 모달 -->\n");
      out.write("                                      <div class=\"s-modal modal fade\" id=\"score1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                                        aria-hidden=\"true\">\n");
      out.write("                                        <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                                          <div class=\"modal-content\">\n");
      out.write("                                            <div class=\"modal-header\">\n");
      out.write("                                              <h5 class=\"modal-title\" id=\"exampleModalLabel\">김진원</h5>\n");
      out.write("                                              <button type=\"button\" class=\"close\" data-dismiss=\"\" aria-label=\"Close\">\n");
      out.write("                                                <span aria-hidden=\"true\">×</span>\n");
      out.write("                                              </button>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"modal-body\">\n");
      out.write("                                              <!-- 문답시작 -->\n");
      out.write("                                              <div class=\"row\">\n");
      out.write("												<table class=\"table table-bordered mx-5\">\n");
      out.write("													<thead style=\"background-color: lightgray;\">\n");
      out.write("														<tr>\n");
      out.write("															<td width=\"100\">문제</td>\n");
      out.write("															<td>1. 연산자 종류에 대해 작성하시오.</td>\n");
      out.write("														</tr>\n");
      out.write("													</thead>\n");
      out.write("														\n");
      out.write("													<tbody>\n");
      out.write("														<tr>\n");
      out.write("															<td>학생답안</td>\n");
      out.write("															<td>-, *, +, /, %</td>\n");
      out.write("														</tr>\n");
      out.write("													</tbody>\n");
      out.write("													\n");
      out.write("													<tfoot>\n");
      out.write("														<tr>\n");
      out.write("															<td>모범답안</td>\n");
      out.write("															<td style=\"color: blue\">-, *, +, /, %</td>\n");
      out.write("														</tr>\n");
      out.write("													</tfoot>\n");
      out.write("												</table>\n");
      out.write("                                              </div>\n");
      out.write("                                              \n");
      out.write("                                              <hr>\n");
      out.write("                                              \n");
      out.write("                                             <div class=\"row\">\n");
      out.write("	                                              <table class=\"table table-bordered mx-5\">\n");
      out.write("													<thead style=\"background-color: lightgray;\">\n");
      out.write("														<tr>\n");
      out.write("															<td width=\"100\">문제</td>\n");
      out.write("															<td>2. 자료형 종류에 대해 작성하시오.</td>\n");
      out.write("														</tr>\n");
      out.write("													</thead>\n");
      out.write("														\n");
      out.write("													<tbody>\n");
      out.write("														<tr>\n");
      out.write("															<td>학생답안</td>\n");
      out.write("															<td>short, int, float</td>\n");
      out.write("														</tr>\n");
      out.write("													</tbody>\n");
      out.write("													\n");
      out.write("													<tfoot>\n");
      out.write("														<tr>\n");
      out.write("															<td>모범답안</td>\n");
      out.write("															<td style=\"color: blue\">short, int, float, double, byte, long, char</td>\n");
      out.write("														</tr>\n");
      out.write("													</tfoot>\n");
      out.write("												</table>\n");
      out.write("                                             </div>\n");
      out.write("                                             \n");
      out.write("                                             <hr>\n");
      out.write("                                              <!-- 문답끝 -->\n");
      out.write("                                            <div class=\"modal-footer\">\n");
      out.write("	                                            <div class=\"d-flex flex-row mb-1 p-2\">\n");
      out.write("												  <div class=\"py-4\">점수입력 : </div>\n");
      out.write("												  <div class=\"p-2\">\n");
      out.write("		                                                <div class=\"form-group\">\n");
      out.write("														    <input class=\"form-control\" id=\"input-score\" type=\"number\" onkeyPress=\"javascript:checkInputNum();\" value=\"10\" min=\"0\" maxlength=\"100\" placeholder=\"점수를 입력하세요\">\n");
      out.write("														</div>\n");
      out.write("												  </div>\n");
      out.write("												</div>\n");
      out.write("                                              <button type=\"button\" class=\"btn btn-danger btn-pill\" data-dismiss=\"\" id=\"close\">닫기</button>\n");
      out.write("                                              <button type=\"button\" class=\"btn btn-primary btn-pill\">저장</button>\n");
      out.write("                                            </div>\n");
      out.write("                                          </div>\n");
      out.write("                                        </div>\n");
      out.write("                                      </div>\n");
      out.write("                                      <!-- 채점 모달 끝 -->\n");
      out.write("                                      \n");
      out.write("                                      \n");
      out.write("            <script>\n");
      out.write("            function checkInputNum(){\n");
      out.write("                if ((event.keyCode < 48) || (event.keyCode > 57)){\n");
      out.write("                    event.returnValue = false;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("              $(function(){\n");
      out.write("                $(\".test-start\").click(function(){\n");
      out.write("                  let title = $(this).parents(\"tr\").children().eq(2).html();\n");
      out.write("                  \n");
      out.write("                  if(confirm(\"[\" + title + \"] 평가를 시작하시겠습니까?\")){\n");
      out.write("                    alert(\"평가가 시작되었습니다\");\n");
      out.write("                    $(this).attr(\"disabled\", true);\n");
      out.write("                    $(this).next().attr(\"disabled\", false);\n");
      out.write("                    $(this).next().next().attr(\"disabled\", false);\n");
      out.write("                  }\n");
      out.write("                  \n");
      out.write("                })\n");
      out.write("\n");
      out.write("                $(\".close, #close\").click(function(){\n");
      out.write("                  let getId = '#' + $(this).parents(\".s-modal\").attr('id');\n");
      out.write("                  console.log(getId);\n");
      out.write("                  $(getId).modal('hide');\n");
      out.write("                  \n");
      out.write("                })\n");
      out.write("\n");
      out.write("                $(\".test-end\").click(function(){\n");
      out.write("                  if(confirm(\"평가를 종료 하시겠습니까?\")){\n");
      out.write("                    $(this).prev().attr(\"disabled\", true);\n");
      out.write("                    $(this).attr(\"disabled\", true);\n");
      out.write("                    alert(\"평가가 종료되었습니다\");\n");
      out.write("                  }\n");
      out.write("                })\n");
      out.write("              })\n");
      out.write("\n");
      out.write("			  $(document).ready(function(){\n");
      out.write("				   $(document).on(\"keyup\",\"#input-score\", function(){\n");
      out.write("					 if ($(this).val() > 100){\n");
      out.write("						 $(this).val(100);\n");
      out.write("					 }\n");
      out.write("					 \n");
      out.write("					 if ($(this).val() < 0){\n");
      out.write("						 $(this).val(0);\n");
      out.write("					 }\n");
      out.write("				   })\n");
      out.write("			  })\n");
      out.write("            </script>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
