/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-11 00:35:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.instructor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class studentForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>학생게시판</title>\r\n");
      out.write("\r\n");
      out.write("<style> \r\n");
      out.write("div {\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".leftMenu {\r\n");
      out.write("    width: 25%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background: #f0f0f1;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contents{\r\n");
      out.write("    width: 75%;\r\n");
      out.write("    margin-left: 413px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".leftMenu .topBtnBox {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 48px;\r\n");
      out.write("    padding: 7px 9px 7px 7px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".leftMenu .topBtnBox .topBtnBox_left {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 60%;\r\n");
      out.write("}\r\n");
      out.write("<!--학생등록버튼-->\r\n");
      out.write(".leftMenu .topBtnBox .topBtnBox_right {\r\n");
      out.write("    float: right;\r\n");
      out.write("    padding-left: 4px;\r\n");
      out.write("    width: 40%;\r\n");
      out.write("}\r\n");
      out.write("button.bBtn03 {\r\n");
      out.write("    height: 33px;\r\n");
      out.write("    padding: 0 8px;\r\n");
      out.write("    padding-bottom: 3px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    text-shadow: 0 0 2px #000;\r\n");
      out.write("    letter-spacing: -0.5px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background-color: #02068D;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    margin-left: 35px;\r\n");
      out.write("}\r\n");
      out.write("<!--상단 카테고리-->\r\n");
      out.write(".leftMenu .topBtnBox2Line {\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("select:not(:-internal-list-box) {\r\n");
      out.write("    overflow: visible !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("    display: table-cell;\r\n");
      out.write("    vertical-align: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    border-collapse: separate;\r\n");
      out.write("    text-indent: initial;\r\n");
      out.write("    border-spacing: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".leftMenu .topBtnBox2Line .search select, .leftMenu .topBtnBox2Line .search input[type=text] {\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    border: 1px solid #444959;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    margin-top: 3px;\r\n");
      out.write("}\r\n");
      out.write("<!--학생조회-->\r\n");
      out.write("tbody {\r\n");
      out.write("    display: table-row-group;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("}\r\n");
      out.write("tr {\r\n");
      out.write("    display: table-row;\r\n");
      out.write("    vertical-align: inherit;\r\n");
      out.write("    border-color: inherit;\r\n");
      out.write("}\r\n");
      out.write("<!--컨텐츠-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#memberInfo {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: solid 2px black;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("<!--프로필사진-->\r\n");
      out.write("#photoArea {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#photoArea .photoGroup {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 190px;\r\n");
      out.write("    height: 250px;\r\n");
      out.write("    background: #ccc;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("    margin-left: 30px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("#photoArea .photoGroup img {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body marginwidth=\"0\" marginheight=\"0\" style=\"zoom: 1;\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../instructor/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("       <div style=\"height: 1000px;; padding-left: 250px;\"class=\"all\">\r\n");
      out.write("        <div class=\"leftMenu\">\r\n");
      out.write("            <div class=\"topBtnBox\" style=\"background-color: #979cc4; height: 75px;\">   \r\n");
      out.write("                <div class=\"topBtnBox_left\"><h1 style=\"font-size: 20px; color: white; margin-top: 27px;\">학생관리</h1></div>\r\n");
      out.write("                <div class=\"topBtnBox_right\">\r\n");
      out.write("                    <button type=\"button\" class=\"bBtn03\"onclick=\"locationGo('member','0','W','student_write.asp','left_student.asp');\" title=\"\"><strong style=\"font-size:13pt\">+</strong> 학생등록</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"topBtnBox2Line\" style=\"margin-top: 15px;\">\r\n");
      out.write("                <form name=\"fSch\" method=\"get\">\r\n");
      out.write("                <div class=\"search\">\r\n");
      out.write("                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"margin-left: 7px;\">\r\n");
      out.write("                        <tbody >\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <select style=\"width:95px; border-radius: 3px;\" name=\"nowState\" id=\"nowState\">\r\n");
      out.write("                                    <option value=\"9\">수강전체</option>\r\n");
      out.write("                                    <option value=\"2\" selected=\"\">수강생</option>\r\n");
      out.write("                                    <option value=\"1\">대기생</option>\r\n");
      out.write("                                    <option value=\"8\">휴강생</option>\r\n");
      out.write("                                    <option value=\"0\">퇴원생</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <select style=\"width:226px; border-radius: 3px;\" name=\"classNo\" id=\"classNo\">\r\n");
      out.write("                                    <option value=\"\" selected=\"\">---- 학급 선택 ----</option>\r\n");
      out.write("                                    \r\n");
      out.write("                                        <option value=\"8655\">자바프로그래밍</option>\r\n");
      out.write("                                    \r\n");
      out.write("                                        <option value=\"8663\">JAVA</option>\r\n");
      out.write("                                    \r\n");
      out.write("                                </select>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td rowspan=\"2\" valign=\"top\" align=\"right\"><button type=\"button\" class=\"bBtn08\" style=\"width:70px; height:65px;background-color: #02068D; border-radius: 5px; color: white; margin-right: 14px;\" \r\n");
      out.write("                                onclick=\"document.fSch.nowState.disabled=false;document.fSch.classNo.disabled=false;document.fSch.keytype.disabled=false;document.fSch.submit();\">검색</button></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <select style=\"width:95px; border-radius: 3px;\" name=\"keytype\" id=\"keytype\">\r\n");
      out.write("                                    <option value=\"name\">학생이름</option>\r\n");
      out.write("                                    <option value=\"id\">학생아이디</option>\r\n");
      out.write("                                    <option value=\"rfcardNo\">학생학원번호</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                                <input type=\"text\" name=\"keyword\" id=\"keyword\" style=\"width:226px; border-radius: 3px;\" onfocus=\"javascript:SetCaretAtEnd(document.getElementById('keyword'));\" value=\"\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"leftMemList\" style=\"margin-top: 10px;\">\r\n");
      out.write("                        <tbody style=\"background-color: #979cc4; height: 40px;\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                            <th width=\"30\"><input type=\"checkbox\" name=\"check\" onclick=\"revcheck(this.form);\" title=\"문자발송\" style=\"margin-left: 10px;\"></th>\r\n");
      out.write("                            <th width=\"40\" style=\"color: rgb(255, 255, 255); font-size: 17px;\">No</th>\r\n");
      out.write("                            <th width=\"70\" style=\"color: rgb(255, 255, 255); font-size: 15px;\">이름 <span class=\"up_btn\"><a href=\"javascript:;\" onclick=\"document.fMemPcsList.orderby.value='name asc';document.fMemPcsList.submit();\" style=\"color:#000000;\">▲</a></span><span class=\"up_btn\"><a href=\"javascript:;\" onclick=\"document.fMemPcsList.orderby.value='name desc';document.fMemPcsList.submit();\">▼</a></span></th>\r\n");
      out.write("                            <th width=\"88\" style=\"color: rgb(255, 255, 255); font-size: 15px;\">학생휴대폰</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                 \r\n");
      out.write("                    <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"leftMemList\">\r\n");
      out.write("                                <tbody style=\"height: 40px; color: black;\">\r\n");
      out.write("                                    <tr id=\"listItem_user03\" class=\"on\" onkeydown=\"onItemKeyDown('user03', event);\" onclick=\"showContents('user03');\">\r\n");
      out.write("                                    <td width=\"30\" align=\"center\"><input type=\"checkbox\" name=\"mobileNo\" id=\"listItemMobileNo_user03\" value=\"user03|김누구|\"></td>\r\n");
      out.write("                                    <td width=\"88\" style=\"font-size: 17px;\" align=\"center\" id=\"listItemPcs_user03\">1</td>\r\n");
      out.write("                                    <td width=\"70\" style=\"padding-left:5px; font-size: 15px;\"  id=\"listItemSex_user03\"><div class=\"sex_man\" id=\"listItemName_user03\">김누구</div></td>\r\n");
      out.write("                                    <td align=\"right\" style=\"padding-right:70px; font-size: 15px;\"  id=\"listItemMinab_user03\" class=\"leftStdListMoreOpen\">010-5285-0376</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                                \r\n");
      out.write("                </table>\r\n");
      out.write("                <div style=\"border: solid 1px #02068D\"></div> \r\n");
      out.write("                </form>\r\n");
      out.write("            </div> <!--topBtnBox2Line-->\r\n");
      out.write("\r\n");
      out.write("            </div> <!--leftMenu-->\r\n");
      out.write("            <div class=\"contents\"> \r\n");
      out.write("                <div class=\"infoStyle03\">   \r\n");
      out.write("                    <div id=\"memberInfo\" style=\"background-color: #f8f8f8;\">\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"tableGroup\" style=\"height: 1000px; margin-top: 30px; margin-left: 5px;\">\r\n");
      out.write("                            <div id=\"photoArea\">\r\n");
      out.write("                                <div class=\"photoGroup\" style=\"margin: 20px;\">\r\n");
      out.write("                                    <img id=\"memBerPhoto\" src=\"\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <table cellpadding=\"0\" cellspacing=\"0\" style=\"width:1000px; height: 500px;\">\r\n");
      out.write("                                <colgroup >\r\n");
      out.write("                                    <col width=\"60\">\r\n");
      out.write("                                    <col width=\"100\">\r\n");
      out.write("                                    <col width=\"120\">\r\n");
      out.write("                                    <col width=\"*\">\r\n");
      out.write("                                </colgroup>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">이름 </th>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"memName\" value=\"김누구\" maxlength=\"20\" style=\"width:100%; height: 35px;\" disabled=\"\"></td>\r\n");
      out.write("                                    \r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">성별 </th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"radio\" name=\"sex\" value=\"남\" checked=\"\">남 \r\n");
      out.write("                                        <input type=\"radio\" name=\"sex\" value=\"여\">여\r\n");
      out.write("                                        &nbsp;(26세)\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">아이디 </th>\r\n");
      out.write("                                    <td><input type=\"text\" style=\"width:100%; height: 35px;\" name=\"memId\" value=\"user03\" class=\"readon\" disabled=\"\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">비밀번호 </th>\r\n");
      out.write("                                    <td><input type=\"text\" style=\"width:100%; height: 35px;\" name=\"pw\" value=\"pass03\" maxlength=\"16\" disabled=\"\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">생년월일</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" style=\"width:80px; height: 35px;\" class=\"datepicker hasDatepicker\" readonly=\"\" name=\"birthday\" value=\"1998-12-24\" id=\"dp1680462505816\" disabled=\"\"> \r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>   \r\n");
      out.write("                                <tr>\r\n");
      out.write("                                <th style=\"color: rgb(87, 87, 87);\">이메일</th>\r\n");
      out.write("                                <td><input type=\"text\" name=\"email\" value=\"jane9512@naver.com\" maxlength=\"50\" style=\"width:100%; height: 35px;\" disabled=\"\"></td>\r\n");
      out.write("                                </tr>                          \r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">반</th>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"class\" value=\"361\" maxlength=\"30\" style=\"width:30px; height: 35px;\" disabled=\"\">반</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">휴대전화</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" name=\"pcs\" value=\"010-5285-0376\" maxlength=\"15\" style=\"width:200px; height: 35px;\" disabled=\"\"> \r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"color: rgb(87, 87, 87);\">주소 </th>\r\n");
      out.write("                                    <td colspan=\"3\">\r\n");
      out.write("                                        <div style=\"padding-bottom:5px;\">\r\n");
      out.write("                                            <input type=\"text\" style=\"width:100px; height: 35px;\" name=\"zipcode\" id=\"zipcode\" title=\"우편번호\" value=\"07362\" maxlength=\"5\" onkeyup=\"chkNumeric(this);\" disabled=\"\"> \r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                            <input type=\"text\" style=\"width:41%; height: 35px;\" name=\"address1\" id=\"address1\" value=\"서울시 영등포구 신길동\" maxlength=\"150\" title=\"주소\" disabled=\"\">\r\n");
      out.write("                                            <input type=\"text\" style=\"width:41%; height: 35px;\" name=\"address2\" id=\"address2\" value=\"래미안아파트101동303호\" maxlength=\"50\" title=\"상세주소\" disabled=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                    </form>\r\n");
      out.write("                </div> \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!--전체-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
