/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-04-10 01:24:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.instructor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class taskForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" dir=\"ltr\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/nprogress/nprogress.js\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	tr {\n");
      out.write("      cursor: pointer;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"page-wrapper\">\n");
      out.write("	<div class=\"wrapper\">\n");
      out.write("		<!-- 헤더 -->\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../instructor/common/header.jsp", out, false);
      out.write("\n");
      out.write("		\n");
      out.write("		<div class=\"content-wrapper table-hover\">\n");
      out.write("        <div class=\"content\"><!-- For Components documentaion -->\n");
      out.write("\n");
      out.write("          <!-- 여기서부터  -->\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-md-auto\" style=\"background-color: white;\">\n");
      out.write("              <!-- 과제 등록 패널 -->\n");
      out.write("              <div class=\"row mx-1\" style=\"font-weight: bolder; font-weight: bold;\">과제 컨텐츠</div>\n");
      out.write("              <div class=\"row mx-1\">\n");
      out.write("                <!-- 과제폴더 시작 -->\n");
      out.write("                <div class=\"container\" style=\"height: 600px;\">\n");
      out.write("                  <div class=\"row\">\n");
      out.write("                    \n");
      out.write("                    <div id=\"left\" class=\"span3\">\n");
      out.write("                      <ul id=\"menu-group-1\" class=\"nav menu\">\n");
      out.write("                        <li class=\"item-1 deeper parent active\">\n");
      out.write("                          <a class=\"\" href=\"#\">\n");
      out.write("                            <span data-toggle=\"collapse\" data-parent=\"#menu-group-1\" href=\"#sub-item-1\" class=\"sign\"><i\n");
      out.write("                                class=\"icon-plus icon-white\"></i></span>\n");
      out.write("                            <span class=\"lbl\">자바프로그래밍</span>\n");
      out.write("                          </a>\n");
      out.write("                          <ul class=\"children nav-child unstyled small collapse\" id=\"sub-item-1\">\n");
      out.write("                            \n");
      out.write("                            <!-- 1주차 -->\n");
      out.write("                            <li class=\"item-2 deeper parent active\">\n");
      out.write("                              <a class=\"\" href=\"#\">\n");
      out.write("                                <span data-toggle=\"collapse\" data-parent=\"#menu-group-1\" href=\"#sub-item-2\"\n");
      out.write("                                  class=\"sign\"><i class=\"icon-plus icon-white\"></i></span>\n");
      out.write("                                <span class=\"lbl\">1주차</span>\n");
      out.write("                              </a>\n");
      out.write("                              <ul class=\"children nav-child unstyled small collapse\" id=\"sub-item-2\">\n");
      out.write("                                <li class=\"item-3\">\n");
      out.write("                                  <a class=\"\" href=\"#\">\n");
      out.write("                                    <span class=\"sign\"><i class=\"icon-play\"></i></span>\n");
      out.write("                                    <span class=\"lbl file\">정수의 합</span>\n");
      out.write("                                  </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"item-4\">\n");
      out.write("                                  <a class=\"\" href=\"#\">\n");
      out.write("                                    <span class=\"sign\"><i class=\"icon-play\"></i></span>\n");
      out.write("                                    <span class=\"lbl file\">나머지 계산</span>\n");
      out.write("                                  </a>\n");
      out.write("                                </li>\n");
      out.write("                              </ul>\n");
      out.write("                            </li>\n");
      out.write("  \n");
      out.write("                            <!-- 2주차 -->\n");
      out.write("                            <li class=\"item-5 deeper parent\">\n");
      out.write("                              <a class=\"\" href=\"#\">\n");
      out.write("                                <span data-toggle=\"collapse\" data-parent=\"#menu-group-1\" href=\"#sub-item-5\"\n");
      out.write("                                  class=\"sign\"><i class=\"icon-plus icon-white\"></i></span>\n");
      out.write("                                <span class=\"lbl\">2주차</span>\n");
      out.write("                              </a>\n");
      out.write("                              <ul class=\"children nav-child unstyled small collapse\" id=\"sub-item-5\">\n");
      out.write("                                <li class=\"item-6\">\n");
      out.write("                                  <a class=\"\" href=\"#\">\n");
      out.write("                                    <span class=\"sign\"><i class=\"icon-play\"></i></span>\n");
      out.write("                                    <span class=\"lbl file\">if문실습</span>\n");
      out.write("                                  </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"item-7\">\n");
      out.write("                                  <a class=\"\" href=\"#\">\n");
      out.write("                                    <span class=\"sign\"><i class=\"icon-play\"></i></span>\n");
      out.write("                                    <span class=\"lbl file\">while문 실습</span>\n");
      out.write("                                  </a>\n");
      out.write("                                </li>\n");
      out.write("                              </ul>\n");
      out.write("                            </li>\n");
      out.write("  \n");
      out.write("                          </ul>\n");
      out.write("                        </li>\n");
      out.write("  \n");
      out.write("                      </ul>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("              \n");
      out.write("              \n");
      out.write("              <!-- 과제등록패널 체크박스 -->\n");
      out.write("              <div class=\"row\" style=\"font-size: 12px;\">\n");
      out.write("                <div class=\"d-flex align-items-start flex-column mb-3 mx-2\" style=\"height: 50px;\">\n");
      out.write("                  <h1 class=\"conn\" style=\"display: none;\"></h1>\n");
      out.write("                  <div class=\"custom-control custom-checkbox d-inline-block mr-3 mb-3 conn\">\n");
      out.write("                  </div>\n");
      out.write("                  <!-- 과제 등록 버튼 -->\n");
      out.write("                  <button type=\"button\" class=\"task-btn btn btn-primary my-5 d-flex align-items-end position-absolute\">과제등록하기</button>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              \n");
      out.write("\n");
      out.write("              <!-- 과제폴더 끝 -->\n");
      out.write("              <script>\n");
      out.write("                $(function () {\n");
      out.write("                  $(document).on(\"click\", \"#left ul.nav li.parent > a > span.sign\", function () {\n");
      out.write("                    $(this).find('i:first').toggleClass(\"icon-minus\");\n");
      out.write("                  });\n");
      out.write("\n");
      out.write("                  // Open Le current menu\n");
      out.write("                  $(\"#left ul.nav li.parent.active > a > span.sign\").find('i:first').addClass(\"icon-minus\");\n");
      out.write("                  $(\"#left ul.nav li.current\").parents('ul.children').addClass(\"in\");\n");
      out.write("\n");
      out.write("                  $(\".task-btn\").click(function(){\n");
      out.write("                    if(confirm(\"정말 등록하시겟습니까?\")){\n");
      out.write("                      console.log(\"등록완료\");\n");
      out.write("                      alert(\"등록이 완료되었습니다.\");\n");
      out.write("                    } else {\n");
      out.write("                      console.log(\"등록취소\");\n");
      out.write("                    }\n");
      out.write("                  })\n");
      out.write("\n");
      out.write("                })\n");
      out.write("                \n");
      out.write("                $(document).ready(function(){\n");
      out.write("                  // 과제 추가\n");
      out.write("                  $(document).on(\"click\",\".file\", function(){\n");
      out.write("                    console.log(\"파일 클릭\");\n");
      out.write("                    console.log($(this).html());\n");
      out.write("                    let title = $(this).html();\n");
      out.write("                    $(\".conn\").append(\"<input type=\\\"checkbox\\\" class=\\\"custom-control-input\\\" id=\\\"customCheck1\\\" checked=\\\"checked\\\"> <label class=\\\"custom-control-label\\\" for=\\\"customCheck1\\\">\" + title + \"</label> <label class=\\\"deleteTask\\\" style=\\\"cursor: pointer;\\\">X</label>\");\n");
      out.write("                  })\n");
      out.write("\n");
      out.write("                  // 과제 삭제\n");
      out.write("                  $(document).on(\"click\",\".deleteTask\", function(){\n");
      out.write("                    $(this).parent().children().remove();\n");
      out.write("                    console.log(\"삭제 버튼\");\n");
      out.write("                  });\n");
      out.write("                })\n");
      out.write("              </script>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <!-- 과제목록  -->\n");
      out.write("            <div class=\"col-10\">  \n");
      out.write("              <h6 style=\"font-weight: bolder;\">과제목록</h6>\n");
      out.write("              <hr>\n");
      out.write("              <br>\n");
      out.write("              <div class=\"d-flex flex-row mb-5\">\n");
      out.write("                <div class=\"col-md-auto\">\n");
      out.write("                  <label style=\"margin-right: -10px; font-size: 13px;\">기간별</label>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-auto\">\n");
      out.write("                  <div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\" style=\"font-size: 10px;\">\n");
      out.write("                    <button type=\"button\" class=\"period btn btn-primary\" value=\"today\"\n");
      out.write("                      style=\"height: 30px; line-height: 9px; font-size: 10px;\">오늘</button>\n");
      out.write("                    <button type=\"button\" class=\"period btn btn-primary\" value=\"week\"\n");
      out.write("                      style=\"height: 30px; line-height: 9px; font-size: 12px;\">일주일</button>\n");
      out.write("                    <button type=\"button\" class=\"period btn btn-primary\" value=\"month\"\n");
      out.write("                      style=\"height: 30px; line-height: 9px; font-size: 12px;\">1개월</button>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-auto\">\n");
      out.write("                  <label style=\"margin-right: 5px;\">기간</label>\n");
      out.write("                  <input type=\"date\" class=\"start\">\n");
      out.write("                  <label>~</label>\n");
      out.write("                  <input type=\"date\" class=\"start\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-auto\">\n");
      out.write("                  <div class=\"custom-control custom-checkbox d-inline-block mr-3 mb-3 py-1\">\n");
      out.write("                    <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck3\" checked=\"checked\">\n");
      out.write("                    <label class=\"custom-control-label\" for=\"customCheck3\">미완료 과제</label>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-auto\" style=\"margin-left: -30px;\">\n");
      out.write("                  <input type=\"text\" style=\"margin-top: 3px;\" placeholder=\"과제검색\">\n");
      out.write("                  <button type=\"button\" class=\"btn btn-primary px-1 py-1\" style=\"height: 29px;\">검색</button>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("              <table class=\"table\" style=\"text-align: center;\">\n");
      out.write("                <thead style=\"background-color: lightgray;\">\n");
      out.write("                  <tr>\n");
      out.write("                    <th scope=\"col\">번호</th>\n");
      out.write("                    <th scope=\"col\">제목</th>\n");
      out.write("                    <th scope=\"col\">학생명</th>\n");
      out.write("                    <th scope=\"col\">완료여부</th>\n");
      out.write("                    <th>채점</th>\n");
      out.write("                    <th>수정</th>\n");
      out.write("                  </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                  <tr>\n");
      out.write("                    <td scope=\"row\" style=\"width: 60px;\">1</td>\n");
      out.write("                    <td>정수의 합</td>\n");
      out.write("                    <td>조진원</td>\n");
      out.write("                    <td>완료</td>\n");
      out.write("                    <td><button type=\"button\" class=\"btn btn-primary\" style=\"height: 30px; line-height: 15px;\"\n");
      out.write("                        data-toggle=\"modal\" data-target=\"#grade1\">채점</button></td>\n");
      out.write("                    <td><button type=\"button\" class=\"btn btn-primary\" style=\"height: 30px; line-height: 15px;\"\n");
      out.write("                        data-toggle=\"modal\" data-target=\"#grade2\" disabled>수정</button></td>\n");
      out.write("                    <!-- 채점 모달1 시작 -->\n");
      out.write("                    <div class=\"modal fade\" id=\"grade1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                      aria-hidden=\"true\">\n");
      out.write("                      <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                        <div class=\"modal-content\">\n");
      out.write("                          <div class=\"modal-header\">\n");
      out.write("                            <h5 class=\"modal-title\" id=\"exampleModalLabel\">정수의합 (조진원)</h5>\n");
      out.write("                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                              <span aria-hidden=\"true\">×</span>\n");
      out.write("                            </button>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"modal-body\">\n");
      out.write("                          	  <!-- 학생답 시작 -->\n");
      out.write("                              <div class=\"card\">\n");
      out.write("								    <img class=\"card-img-top\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/test1.PNG\" alt=\"Card image cap\">\n");
      out.write("								    <div class=\"card-body\">\n");
      out.write("									  <div class=\"row\">\n");
      out.write("									  	<div class=\"col-md-auto\">\n");
      out.write("								      	<h5 class=\"card-title \">답변</h5>\n");
      out.write("											<textarea rows=\"5\" cols=\"80\" style=\"resize: none;\"></textarea>\n");
      out.write("									  	</div>\n");
      out.write("									  	<div class=\"col-md-auto\">\n");
      out.write("									  	 <h5 class=\"card-title \">점수</h5>\n");
      out.write("											  <div class=\"form-group\">\n");
      out.write("											    <select class=\"form-control rounded-pill\" id=\"exampleFormControlSelect13\">\n");
      out.write("											      <option>1</option>\n");
      out.write("											      <option>2</option>\n");
      out.write("											      <option>3</option>\n");
      out.write("											      <option>4</option>\n");
      out.write("											      <option>5</option>\n");
      out.write("											    </select>\n");
      out.write("											  </div>\n");
      out.write("									  	</div>\n");
      out.write("									  </div>\n");
      out.write("								    </div>\n");
      out.write("								  </div>\n");
      out.write("							  </div>\n");
      out.write("							  <!-- 학생답끝 -->\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"modal-footer\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-pill\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary btn-pill\">Save Changes</button>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- 채점 모달 끝 -->\n");
      out.write("                    \n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td scope=\"row\" style=\"width: 60px;\">2</td>\n");
      out.write("                    <td>정수의 합</td>\n");
      out.write("                    <td>김진원</td>\n");
      out.write("                    <td>완료</td>\n");
      out.write("                    <td>50/100</td>\n");
      out.write("                    <td style=\"width: 150px;\"><button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("                        style=\"height: 30px; line-height: 15px;\" data-toggle=\"modal\" data-target=\"#update1\">수정</button>\n");
      out.write("                    </td>\n");
      out.write("                    <!-- 채점 모달2 시작 -->\n");
      out.write("                    <div class=\"modal fade\" id=\"update1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                      aria-hidden=\"true\">\n");
      out.write("                      <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                        <div class=\"modal-content\">\n");
      out.write("                          <div class=\"modal-header\">\n");
      out.write("                            <h5 class=\"modal-title\" id=\"exampleModalLabel\">정수의합 (김진원)</h5>\n");
      out.write("                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                              <span aria-hidden=\"true\">×</span>\n");
      out.write("                            </button>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"modal-body\">\n");
      out.write("                            Modal body text goes here.\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"modal-footer\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-pill\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary btn-pill\">Save Changes</button>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- 채점 모달 끝 -->\n");
      out.write("                  </tr>\n");
      out.write("\n");
      out.write("                  <!-- 미완료  -->\n");
      out.write("                  <tr>\n");
      out.write("                    <td scope=\"row\" style=\"width: 60px;\">3</td>\n");
      out.write("                    <td>정수의 합</td>\n");
      out.write("                    <td>이진원</td>\n");
      out.write("                    <td>미완료</td>\n");
      out.write("                    <td>0/100</td>\n");
      out.write("                    <td style=\"width: 150px;\"><button type=\"button\" class=\"btn btn-primary\"\n");
      out.write("                        style=\"height: 30px; line-height: 15px;\" data-toggle=\"modal\" data-target=\"#update1\"\n");
      out.write("                        disabled>수정</button></td>\n");
      out.write("                    <!-- 채점 모달2 시작 -->\n");
      out.write("                    <div class=\"modal fade\" id=\"update1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\n");
      out.write("                      aria-hidden=\"true\">\n");
      out.write("                      <div class=\"modal-dialog modal-xl\" role=\"document\">\n");
      out.write("                        <div class=\"modal-content\">\n");
      out.write("                          <div class=\"modal-header\">\n");
      out.write("                            <h5 class=\"modal-title\" id=\"exampleModalLabel\">정수의합 (김진원)</h5>\n");
      out.write("                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                              <span aria-hidden=\"true\">×</span>\n");
      out.write("                            </button>\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"modal-body\">\n");
      out.write("                            Modal body text goes here.\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"modal-footer\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-pill\" data-dismiss=\"modal\">Close</button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary btn-pill\">Save Changes</button>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- 채점 모달 끝 -->\n");
      out.write("                  </tr>\n");
      out.write("                </tbody>\n");
      out.write("              </table>\n");
      out.write("\n");
      out.write("              <!-- 페이징 -->\n");
      out.write("              <div class=\"card card-default align-items-center\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                  <h2></h2>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("              \n");
      out.write("                  <nav aria-label=\"Page navigation example\">\n");
      out.write("                    <ul class=\"pagination\">\n");
      out.write("                      <li class=\"page-item\">\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\n");
      out.write("                          <span aria-hidden=\"true\" class=\"mdi mdi-chevron-left\"></span>\n");
      out.write("                          <span class=\"sr-only\">Previous</span>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"page-item active\">\n");
      out.write("                        <a class=\"page-link\" href=\"#\">1</a>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"page-item\">\n");
      out.write("                        <a class=\"page-link\" href=\"#\">2</a>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"page-item\">\n");
      out.write("                        <a class=\"page-link\" href=\"#\">3</a>\n");
      out.write("                      </li>\n");
      out.write("                      <li class=\"page-item\">\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\n");
      out.write("                          <span aria-hidden=\"true\" class=\"mdi mdi-chevron-right\"></span>\n");
      out.write("                          <span class=\"sr-only\">Next</span>\n");
      out.write("                        </a>\n");
      out.write("                      </li>\n");
      out.write("                    </ul>\n");
      out.write("                  </nav>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("	</div>\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("      <script src=\"//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
